# Generated by Django 6.0.4 on 2026-04-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('caregiver', 'Caregiver'), ('resident', 'Resident'), ('stockkeeper', 'Stock Keeper'), ('doctor', 'Doctor')], max_length=20),
        ),
    ]
