# Generated by Django 6.0.4 on 2026-04-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('caregiver', 'Caregiver'), ('resident', 'Resident'), ('stockkeeper', 'Stock Keeper'), ('doctor', 'Doctor')], max_length=20),
        ),
    ]
