# Generated by Django 6.0.4 on 2026-04-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('general_ward', 'General Ward'), ('icu', 'ICU'), ('cardiology_dept', 'Cardiology Department'), ('neurology_dept', 'Neurology Department'), ('orthopedics_dept', 'Orthopedics Department'), ('outpatient', 'Outpatient Department'), ('emergency', 'Emergency'), ('other', 'Other')], default='general_ward', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general', 'General Medicine'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('endocrinology', 'Endocrinology'), ('nephrology', 'Nephrology'), ('pulmonology', 'Pulmonology'), ('gastroenterology', 'Gastroenterology'), ('ophthalmology', 'Ophthalmology'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('oncology', 'Oncology'), ('other', 'Other')], default='general', max_length=50),
        ),
    ]
