# Generated by Django 4.2 on 2026-04-21 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=15)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('medical_history', models.TextField(blank=True)),
                ('assigned_caregiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('pulse_rate', models.IntegerField()),
                ('oxygen_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('blood_sugar', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='residents.residentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('test_name', models.CharField(max_length=100)),
                ('result_value', models.FloatField()),
                ('normal_range', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('is_critical', models.BooleanField(default=False)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='residents.residentprofile')),
            ],
        ),
    ]
