# Generated by Django 6.0.4 on 2026-04-27 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discharged', 'Discharged')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='AIHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='Low', max_length=20)),
                ('summary', models.TextField()),
                ('factors', models.TextField(blank=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='residents.residentprofile')),
            ],
        ),
    ]
